// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ubbqfkuqomemfhktobjh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InViYnFma3Vxb21lbWZoa3RvYmpoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0NDkwNzEsImV4cCI6MjA2MzAyNTA3MX0.vdw_fHytoL3hvZhVxR6Li5o9_scJf5_5_HR9G4T8vfM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);